# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Jan 24 13:58:27 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Soundgen(object):
    def setupUi(self, Soundgen):
        Soundgen.setObjectName("Soundgen")
        Soundgen.resize(620, 412)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Soundgen)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 581, 301))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_7)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 271, 111))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.shapeDial2 = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.shapeDial2.setMaximum(3)
        self.shapeDial2.setPageStep(3)
        self.shapeDial2.setTracking(True)
        self.shapeDial2.setNotchesVisible(True)
        self.shapeDial2.setObjectName("shapeDial2")
        self.gridLayout_2.addWidget(self.shapeDial2, 0, 0, 1, 1)
        self.octaveDial2 = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.octaveDial2.setMaximum(4)
        self.octaveDial2.setPageStep(1)
        self.octaveDial2.setProperty("value", 2)
        self.octaveDial2.setNotchesVisible(True)
        self.octaveDial2.setObjectName("octaveDial2")
        self.gridLayout_2.addWidget(self.octaveDial2, 0, 1, 1, 1)
        self.phaseDial2 = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.phaseDial2.setMaximum(360)
        self.phaseDial2.setProperty("value", 180)
        self.phaseDial2.setNotchesVisible(True)
        self.phaseDial2.setObjectName("phaseDial2")
        self.gridLayout_2.addWidget(self.phaseDial2, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 3, 1, 1)
        self.pitchDial2 = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.pitchDial2.setMaximum(200)
        self.pitchDial2.setPageStep(50)
        self.pitchDial2.setProperty("value", 100)
        self.pitchDial2.setNotchesVisible(True)
        self.pitchDial2.setObjectName("pitchDial2")
        self.gridLayout_2.addWidget(self.pitchDial2, 0, 2, 1, 1)
        self.gridLayout_2.setRowStretch(0, 8)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_5.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 271, 111))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.shapeDial3 = QtWidgets.QDial(self.gridLayoutWidget_4)
        self.shapeDial3.setMaximum(3)
        self.shapeDial3.setPageStep(3)
        self.shapeDial3.setTracking(True)
        self.shapeDial3.setNotchesVisible(True)
        self.shapeDial3.setObjectName("shapeDial3")
        self.gridLayout_3.addWidget(self.shapeDial3, 0, 0, 1, 1)
        self.octaveDial3 = QtWidgets.QDial(self.gridLayoutWidget_4)
        self.octaveDial3.setMaximum(4)
        self.octaveDial3.setPageStep(1)
        self.octaveDial3.setProperty("value", 2)
        self.octaveDial3.setNotchesVisible(True)
        self.octaveDial3.setObjectName("octaveDial3")
        self.gridLayout_3.addWidget(self.octaveDial3, 0, 1, 1, 1)
        self.phaseDial3 = QtWidgets.QDial(self.gridLayoutWidget_4)
        self.phaseDial3.setMaximum(360)
        self.phaseDial3.setProperty("value", 180)
        self.phaseDial3.setNotchesVisible(True)
        self.phaseDial3.setObjectName("phaseDial3")
        self.gridLayout_3.addWidget(self.phaseDial3, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 3, 1, 1)
        self.pitchDial3 = QtWidgets.QDial(self.gridLayoutWidget_4)
        self.pitchDial3.setMaximum(200)
        self.pitchDial3.setPageStep(50)
        self.pitchDial3.setProperty("value", 100)
        self.pitchDial3.setNotchesVisible(True)
        self.pitchDial3.setObjectName("pitchDial3")
        self.gridLayout_3.addWidget(self.pitchDial3, 0, 2, 1, 1)
        self.gridLayout_3.setRowStretch(0, 8)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_5.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_9)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 271, 111))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.ampDial1 = QtWidgets.QDial(self.gridLayoutWidget_5)
        self.ampDial1.setProperty("value", 50)
        self.ampDial1.setNotchesVisible(True)
        self.ampDial1.setObjectName("ampDial1")
        self.gridLayout_4.addWidget(self.ampDial1, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 1, 1, 1)
        self.ampDial2 = QtWidgets.QDial(self.gridLayoutWidget_5)
        self.ampDial2.setProperty("value", 50)
        self.ampDial2.setNotchesVisible(True)
        self.ampDial2.setObjectName("ampDial2")
        self.gridLayout_4.addWidget(self.ampDial2, 0, 1, 1, 1)
        self.ampDial3 = QtWidgets.QDial(self.gridLayoutWidget_5)
        self.ampDial3.setProperty("value", 50)
        self.ampDial3.setNotchesVisible(True)
        self.ampDial3.setObjectName("ampDial3")
        self.gridLayout_4.addWidget(self.ampDial3, 0, 2, 1, 1)
        self.gridLayout_4.setRowStretch(0, 8)
        self.gridLayout_5.addWidget(self.groupBox_9, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 271, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.shapeDial1 = QtWidgets.QDial(self.gridLayoutWidget)
        self.shapeDial1.setMaximum(3)
        self.shapeDial1.setPageStep(3)
        self.shapeDial1.setTracking(True)
        self.shapeDial1.setNotchesVisible(True)
        self.shapeDial1.setObjectName("shapeDial1")
        self.gridLayout.addWidget(self.shapeDial1, 0, 0, 1, 1)
        self.octaveDial1 = QtWidgets.QDial(self.gridLayoutWidget)
        self.octaveDial1.setMaximum(4)
        self.octaveDial1.setPageStep(1)
        self.octaveDial1.setProperty("value", 2)
        self.octaveDial1.setNotchesVisible(True)
        self.octaveDial1.setObjectName("octaveDial1")
        self.gridLayout.addWidget(self.octaveDial1, 0, 1, 1, 1)
        self.phaseDial1 = QtWidgets.QDial(self.gridLayoutWidget)
        self.phaseDial1.setMaximum(360)
        self.phaseDial1.setProperty("value", 180)
        self.phaseDial1.setNotchesVisible(True)
        self.phaseDial1.setObjectName("phaseDial1")
        self.gridLayout.addWidget(self.phaseDial1, 0, 3, 1, 1)
        self.pitchDial1 = QtWidgets.QDial(self.gridLayoutWidget)
        self.pitchDial1.setMaximum(200)
        self.pitchDial1.setPageStep(50)
        self.pitchDial1.setProperty("value", 100)
        self.pitchDial1.setNotchesVisible(True)
        self.pitchDial1.setObjectName("pitchDial1")
        self.gridLayout.addWidget(self.pitchDial1, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.gridLayout.setRowStretch(0, 8)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Soundgen)
        self.textEdit.setGeometry(QtCore.QRect(20, 320, 581, 70))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Soundgen)
        QtCore.QMetaObject.connectSlotsByName(Soundgen)

    def retranslateUi(self, Soundgen):
        _translate = QtCore.QCoreApplication.translate
        Soundgen.setWindowTitle(_translate("Soundgen", "Dialog"))
        self.groupBox_7.setTitle(_translate("Soundgen", "Osc 2"))
        self.label_5.setText(_translate("Soundgen", "Shape"))
        self.label_6.setText(_translate("Soundgen", "Octave"))
        self.label_7.setText(_translate("Soundgen", "Pitch"))
        self.label_8.setText(_translate("Soundgen", "Phase"))
        self.groupBox_8.setTitle(_translate("Soundgen", "Osc 3"))
        self.label_9.setText(_translate("Soundgen", "Shape"))
        self.label_10.setText(_translate("Soundgen", "Octave"))
        self.label_11.setText(_translate("Soundgen", "Pitch"))
        self.label_12.setText(_translate("Soundgen", "Phase"))
        self.groupBox_9.setTitle(_translate("Soundgen", "Mixer"))
        self.label_15.setText(_translate("Soundgen", "3"))
        self.label_13.setText(_translate("Soundgen", "1"))
        self.label_14.setText(_translate("Soundgen", "2"))
        self.groupBox_6.setTitle(_translate("Soundgen", "Osc 1"))
        self.label.setText(_translate("Soundgen", "Shape"))
        self.label_2.setText(_translate("Soundgen", "Octave"))
        self.label_3.setText(_translate("Soundgen", "Pitch"))
        self.label_4.setText(_translate("Soundgen", "Phase"))
        self.textEdit.setHtml(_translate("Soundgen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Shape: Sine, Square, Sawtooth, Triangle</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Octave: 32\', 16\', 8\', 4\', 2\'</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pitch: -1, 0, 1.  1 is one octave up, -1 is one octave down</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Phase: Lag from 0 - 360 deg</p></body></html>"))

